### ISSUE TITLE
0+0

### ISSUE THREAD

**Issue by tonyday567** [SamuelSchlesinger/Gaia#1]
Not sure what's up here.  `:t 0` is a `Num`, but `:t (0::Integer)` is `Integer`

```
λ: (0 :: Integer) + (0 :: Integer)

<interactive>:30:1: error:
    • Couldn't match representation of type ‘Gaia.Orphans.Integer.Add’
                               with that of ‘Integer’
        arising from a use of ‘+’
      The data constructor ‘Gaia.Orphans.Integer.Add’
        of newtype ‘Gaia.Orphans.Integer.Add’ is not in scope
    • In the expression: (0 :: Integer) + (0 :: Integer)
      In an equation for ‘it’: it = (0 :: Integer) + (0 :: Integer)
```

Same error on `λ: (0 :: Integer) * (0 :: Integer)` (Looking for Integer.Add)

**Comment by tonyday567** [comment]
I usually find for this stuff it's best to work backwards from concrete examples.  eg, this should be ok in ghci:

```
λ: 1+1
```

**Comment by SamuelSchlesinger** [comment]
All of the constructors through which you'd like to do this sort of representational equality based coercion on must be in scope for the compiler to provide proof of the equality. This is fine with qualified imports but slightly annoying otherwise.

**Comment by tonyday567** [comment]
Ok, so Add etc must be exported, and then it's cool?

**Comment by tonyday567** [comment]
#5 fixes

**Comment by SamuelSchlesinger** [comment]
Yeah exactly, at least that's what it seems so far. You may be able to say
something like type role Add representational but I don't have time to do
this until later.

On Oct 23, 2016 3:20 PM, "Tony Day" notifications@github.com wrote:

Ok, so Add etc must be exported, and then it's cool?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/SamuelSchlesinger/Gaia/issues/1#issuecomment-255608219,
or mute the thread
